config/routes.rb
Rails.application.routes.draw do

  root 'games#index'

  arrayMap = (1..6).map { |x| %Q(get 'index#{x}'\n)}
  arrayMapReduce = arrayMap.reduce { |x,y| x+y }

  resources :welcome do
    collection do
      get 'index'
      get 'demo'
      get 'write'
      get 'write_idioms'
      get 'read'
      eval(arrayMapReduce)
    end
  end 

  resources :games do
    resources :visitors
    member do
      get 'stage1'
      get 'stage2'
      get 'stage_idioms'
      get 'server1'
      get 'server2'
      get 'server_idioms'
      get 'record'
      get 'tvwall'
    end
    collection do
      get 'get_game_data'
    end
  end

end

app/models/game.rb
class Game < ActiveRecord::Base

  has_many :visitors
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  @@game = 0
  @@second = 0
  @@stage = ""

  def index
    @games = Game.all
    @game = Game.new
  end

  def show
    @game = Game.find(params[:id])
    @visitors = @game.visitors
  end

  def create
    @game = Game.new

    @game.save

    redirect_to game_path(@game)
  end

  def stage1
    @game = Game.find(params[:id])

    @join_visitors_number = params[:join_visitors_number]
  end

  def stage2
    @game = Game.find(params[:id])

    @join_visitors_number = params[:join_visitors_number]
  end

  def stage_idioms
    @game = Game.find(params[:id])

    @join_visitors_number = params[:join_visitors_number]
  end

  def server1
    @game = Game.find(params[:id])
    @visitors = @game.visitors.where(number: params[:join_visitors_number].split(","))
    @range = 1..@visitors.size
    @second = params[:second]
    @@second = params[:second]

    @@game = params[:id]
    @@stage = "1"
    #@user_unregs = [1,4]
  end

  def server2
    @game = Game.find(params[:id])
    @visitors = @game.visitors.where(number: params[:join_visitors_number].split(","))
    @range = 1..@visitors.size

    @second = params[:second]
    @@second = params[:second]

    @@game = params[:id]
    @@stage = "2"
    #@user_unregs = [1,4]
  end

  def tvwall
    @game = Game.find(params[:id])
    @visitors = @game.visitors.where(number: params[:join_visitors_number].split(","))
    @range = 1..@visitors.size

    @second = params[:second]
    @@second = params[:second]

    #@user_unregs = [1,4]
  end

  def server_idioms
    @game = Game.find(params[:id])
    @visitors = @game.visitors.where(number: params[:join_visitors_number].split(","))
    @range = 1..@visitors.size

    # for idioms stage, rule is 60 seconds
    @second = "60"
    @@second = "60"

    @@game = params[:id]
    @@stage = "idioms"

  end

  def record
    @game = Game.find(params[:id])
    @visitors = @game.visitors.where(number: params[:join_visitors_number].split(","))
    @range = 1..@visitors.size

    @stage = @@stage
    
  end

  def get_game_data
    if @@game.present?
      @game = Game.find(@@game)
      @visitor = @game.visitors.where(number: params[:id]).first

      respond_to do |format|
        format.json { render :json => { visitor: @visitor,second: @@second,game: @@game, stage: @@stage} }
      end
    else
      respond_to do |format|
        format.json { render :json => "false" }
      end
    end

  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/index.html.erb
<div class="row">
  <div class="col-md-12">
        <%#= link_to "新的比賽",create_game_path,class: "btn btn-lg btn-primary"  %>
        <%= form_for @game , :url => games_path , :html => {:method => :post} do |f| %> 
          <%= f.submit "新的比賽" %>
          <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <h2>過去的比賽：</h2>
    <% if @games.present? %>
    <% @games.each do |g| %>
    <%= link_to "Game#{g.id}-#{g.created_at}",game_path(g) %>
    <br>
    <% end %>
    <% else %>
      尚無記錄
    <% end %>
  </div>
</div>

app/views/games/record.html.erb
      <div class="jumbotron">
        <h2>一字千金 軌跡錄影程式</h2>
      </div>
      <div class="row">
        <% @visitors.each do |x| %>
        <div class="col-md-3">
          <div><%= x.number %>號參賽者</div>
          <div id="console_<%= x.number %>" style="border:1px solid black;line-height:95%;width:100%;height:200px;margin-bottom:12px;overflow:auto;"></div>
        </div>
        <% end %>
      </div>
        
      <% content_for :javascripts do %>
      <%= javascript_include_tag 'pinhole' %>
      <script>

      var preActionCount = 0;
      var fileSaveActionCount = 0;
      var delayTime = 60;

      $(document).ready(function() {
        CR.prop({
          width: 500,
          height: 500,
          lineWidth: 15,
          lineColor: '#333333',
          frameRate: 50,
          backgroundImage: '/assets/block-524.png'
        });

        <% @visitors.each do |visitor| %>
        CR.reg('<%= visitor.number %>');
        <% end %>

        //window.pinhole = new Pinhole('0');
        window.pinhole = new Pinhole('record');
		    window.pinhole.bindEvents();

        window.stopCallBack = function(uid) {
          var scope = window.pinhole;
          var element = $("#console_"+uid);
          var pre = element.html();
          return function(data) {
            element.html(pre + 'STOP<br/>');
            setTimeout((function(dispatcher, id){
              return function(){
                dispatcher.trigger("open_file", {
                  user_id: id,
                  game: <%= @game.id %>,
                  stage: <%= @stage %>
                });
              };
            })(scope.dispatcher, uid), fileSaveActionCount++ * delayTime);


            for (var i = 0, len = data.length; i < len; i++){
              var frameInfo = {
                user_id: uid, 
                timestamp: data[i].stamp.toString(), 
                base64: data[i].base64.split(',')[1]
              };
              setTimeout((function(dispatcher, obj){
                return function(){
                  dispatcher.trigger("save_file", obj);
                };
              })(scope.dispatcher, frameInfo), fileSaveActionCount++ * delayTime);

            }

            setTimeout((function(dispatcher, id){
              return function(){
                dispatcher.trigger("close_file", {
                  user_id: id
                });
              };
            })(scope.dispatcher, uid), fileSaveActionCount++ * delayTime);

            /*
            var i, len;
            scope.dispatcher.trigger("open_file", {
              user_id: uid
            });
            i = 0;
            len = data.length;
            while (i < len) {
              setTimeout((function(dispatcher, last, obj){
                return function(){
                  dispatcher.trigger("save_file", obj);
                  if(last){
                    dispatcher.trigger("close_file", {user_id: obj.user_id});
                  }
                };
              })(scope.dispatcher, (i + 1 == len), {
                user_id: uid, 
                timestamp: data[i].stamp.toString(), 
                base64: data[i].base64.split(',')[1]
              }), fileSaveActionCount * 60);
              
              fileSaveActionCount++;
              i++;
            }
            */

          };
        };

        setInterval(function(){
          if(fileSaveActionCount == preActionCount){
            fileSaveActionCount = preActionCount = 0;
          }else{
            preActionCount = fileSaveActionCount;
          }
        },1300);

        window.startCallBack = function(){
          var id = this.id_;
          var element = $("#console_"+id);
          var pre = element.html();
          element.html(pre + 'START<br/>');
        }

        window.writeToLog = function(pt){
          var id = this.id_;
          var element = $("#console_"+id);
          var pre = element.html();
          element.html(pre + 'stamp:'+pt.stamp + ' x:' + pt.x + ' y:' + pt.y + '<br/>');
        };
      

      });
      </script>
      <% end %>

app/views/games/server1.html.erb
      <div class="jumbotron">
        <h2>一字千金 操作後台</h2>
<!--         <h4>目前上線人數<span id="user_count">0</span>人</h4>
 -->        <% if !@second.nil?  %>
          <h4>倒數計時 <span id="second" style="color:red"><%= @second %></span> 秒 </h4>
        <% else %>
          <h4>不倒數計時</h4>
        <% end %>
      </div>
      <div style="">
        <div class="row">
          <% @visitors.each do |x| %>
          <div class="visitor col-md-3" id="visitor_<%= x.number %>">
          <div class="row">
            <div class="col-md-1">
              <input type="checkbox" name="gamer" value="<%= x.number %>"/>
            </div>
            <div class="col-md-3">
              <%= render_gamer_photo(x.image,"thumb",50,50) %>
              <p><%= x.name %></p>
            </div>
            <div class="col-md-6">
              <canvas id="origin_<%= x.number %>" class="orgincanvas" style="z-index:1"></canvas>
              <img id="yes_<%= x.number %>" src="/assets/O-mark.png" height="150" style="display:none;z-index:10;position:absolute;right:-20px;bottom:8px;" ></img>
              <img id="no_<%= x.number %>" src="/assets/X-Mark.png" height="150" style="display:none;z-index:10;position:absolute;right:-20px;bottom:8px;" ></img>

            </div>
          </div>
          </div>
          <% end %>
        </div>
        <div class="row">
          <div class="col-md-12">
            <input type="checkbox" id="allGamer"/>全選
            <button id="yes_button" style="font-size:15px;">答對</button>
            <button id="no_button" style="font-size:15px;">答錯</button>
            <button id="out_button" style="font-size:15px;">淘汰</button>
            <button id="start_button" style="font-size:15px;">Start</button>
            <button id="stop_button" style="font-size:15px;">Stop</button>
            <button id="clear_button" style="font-size:15px;">Clear All!</button>
          </div>
        </div>
      </div>

      <% content_for :javascripts do %>
      <%= javascript_include_tag 'server' %>
      <script>

      var receiveSubmitHandler = function(o){
        $('#visitor_'+o.user_id).css("background-color", "#e0e0e0");
      };
      window.timeRemaining = parseInt(<%= @second %>);
      window.alarm = null;
      window.open("tvwall?join_visitors_number=<%= params[:join_visitors_number] %>&second=<%= @second %>","tvwallWindow","width=800, height=800");
      window.open("record?join_visitors_number=<%= params[:join_visitors_number] %>&second=<%= @second %>","recordWindow","width=800, height=800");

      $(document).ready(function() {
        CM.prop({
          width: 500,
          height: 500,
          lineWidth: 15,
          lineColor: '#333333',
          targetZoomScale: 0.1,
          backgroundImage: '/assets/block-524.png'
        });
        <% @visitors.each do |visitor| %>
        CM.reg('origin_<%= visitor.number %>');
        <% end %>

        window.chatApp = new ChatApp(500,500,'0');
        window.chatApp.bindEvents();

        var afterAction = function(property){
          var array = [];
          $('[name="gamer"]').each(function(){
            if (this.checked) {
              $('#visitor_'+this.value).css("background-color", "");
              array.push(this.value);
              this.checked = false;
            }
          });
          $('#second').text(window.timeRemaining);
          $('#allGamer').attr('checked',false);

          return array;
        }

        $('#allGamer').click(function(){
          $('[name="gamer"]').each((function(toCheck){
            return function(){
              if (this.disabled == false){
                this.checked = toCheck;
              }
            };
          })(this.checked === true));
        });

        $('#yes_button').click(function(){
          $('[name="gamer"]').each(function(){
            if (this.checked) {
              window.chatApp.right(this.value);
            }
          });
          //alert("answer right:"+array);
        });

        $('#clear_button').click(function(){
            window.chatApp.clearAll();
        });

        /*
        $('#clear_button').click(function() {
            $('[name="gamer"]').each(function() {
               // window.chatApp.clear(this.value);
            }
        });
        */

        $('#no_button').click(function(){
          $('[name="gamer"]').each(function(){
            if (this.checked) {
              window.chatApp.wrong(this.value);
            }
          });
          //alert("answer wrong:"+array);
        });

        $('#out_button').click(function(){
          $('[name="gamer"]').each(function(){
            if (this.checked) {
              CM.unreg('origin_'+this.value);
              this.disabled = true;
            }
          });
          var array = afterAction(this);
          for (var x in array){
            $('#visitor_'+array[x]).attr('style','opacity:0.2');
          }
          //alert("outer:"+array);
        });

        $('#start_button').click(function(){
          if(window.alarm) return;
          $('[name="gamer"]').each(function(){
            if (this.checked) {
              window.chatApp.action(this.value,'start');
              $('#visitor_'+this.value).css("background-color", "");
            }
          });
          if ($('#second').text() != ''){
            window.alarm = setInterval(function(){
              if (parseInt($('#second').text()) != 0){
                $('#second').text(parseInt($('#second').text()) - 1);
              }else{
                clearInterval(window.alarm);
                window.alarm = null;
                $('[name="gamer"]').each(function(){
                  if (this.checked) {
                    window.chatApp.action(this.value,'stop');
                    receiveSubmitHandler({user_id:this.value});
                  }
                });
                var array = afterAction(this);
                //alert("stop:"+array);
              }
            },1000);
          }
          //var array = afterAction(this);
          //alert("start:"+array);
        });

         $('#stop_button').click(function(){
            /*
           $('[name="gamer"]').each(function(){
             if (this.checked) {
               window.chatApp.action(this.value,'stop');
             }
           });
           var array = afterAction(this);
           //alert("stop:"+array);
           */
           clearInterval(window.alarm);
              window.alarm = null;
              $('[name="gamer"]').each(function(){
                if (this.checked) {
                  window.chatApp.action(this.value,'stop');
                  receiveSubmitHandler({user_id:this.value});
                }
              });
              var array = afterAction(this);
         });

      });
      </script>
      <% end %>

app/views/games/server2.html.erb
      <div class="jumbotron">
        <h2>一字千金 操作後台</h2>
<!--         <h4>目前上線人數<span id="user_count">0</span>人</h4>
 -->      </div>
      <div style="">
        <div class="row">
          <% @visitors.each do |x| %>
          <div class="visitor col-md-3" id="visitor_<%= x.number %>">
            <div class="row">
              <div class="col-md-1">
                <input type="checkbox" name="gamer" value="<%= x.number %>"/>
              </div>
              <div class="col-md-3">
                <%= render_gamer_photo(x.image,"thumb",50,50) %>
                <p><%= x.name %></p>
                <span id="second_<%= x.number %>" style="color:red"><%= @second %></span>
              </div>
              <div class="col-md-6">
                <canvas id="origin_<%= x.number %>" class="orgincanvas" style="z-index:1"></canvas>
                <img id="yes_<%= x.number %>" src="/assets/O-mark.png" height="150" style="display:none;z-index:10;position:absolute;right:-20px;bottom:8px;" ></img>
                <img id="no_<%= x.number %>" src="/assets/X-Mark.png" height="150" style="display:none;z-index:10;position:absolute;right:-20px;bottom:8px;" ></img>

              </div>
            </div>
          </div>
          <% end %>
        </div>
        <div class="row">
          <div class="col-md-12">
            <input type="checkbox" id="allGamer"/>全選
            <button id="yes_button" style="font-size:15px;">答對</button>
            <button id="no_button" style="font-size:15px;">答錯</button>
            <button id="out_button" style="font-size:15px;">淘汰</button>
            <button id="start_button" style="font-size:15px;">Start</button>
            <button id="stop_button" style="font-size:15px;">Stop</button>
          </div>
        </div>
      </div>

      <% content_for :javascripts do %>
      <%= javascript_include_tag 'server' %>
      <script>

      var receiveSubmitHandler = function(o){
        $('#visitor_'+o.user_id).css("background-color", "#e0e0e0");
      };
      window.alarm = null;
      window.open("tvwall?join_visitors_number=<%= params[:join_visitors_number] %>&second=<%= @second %>","tvwallWindow","width=800, height=800");
      window.open("record?join_visitors_number=<%= params[:join_visitors_number] %>&second=<%= @second %>","recordWindow","width=800, height=800");

      $(document).ready(function() {
        CM.prop({
          width: 500,
          height: 500,
          lineWidth: 15,
          lineColor: '#333333',
          targetZoomScale: 0.1,
          backgroundImage: '/assets/block-524.png'
        });
        <% @visitors.each do |visitor| %>
        CM.reg('origin_<%= visitor.number %>');
        <% end %>

        window.chatApp = new ChatApp(500,500,'0');
        window.chatApp.bindEvents();

        var afterAction = function(property){
          var array = [];
          $('[name="gamer"]').each(function(){
            if (this.checked) {
              $('#visitor_'+this.value).css("background-color", "");
              array.push(this.value);
              this.checked = false;
            }
          });
          $('#allGamer').attr('checked',false);

          return array;
        }

        $('#allGamer').click(function(){
          $('[name="gamer"]').each((function(toCheck){
            return function(){
              if (this.disabled == false){
                this.checked = toCheck;
              }
            };
          })(this.checked === true));
        });

        $('#yes_button').click(function(){
          $('[name="gamer"]').each(function(){
            if (this.checked) {
              window.chatApp.right(this.value);
            }
          });
          //alert("answer right:"+array);
        });

        $('#no_button').click(function(){
          $('[name="gamer"]').each(function(){
            if (this.checked) {
              window.chatApp.wrong(this.value);
            }
          });
          //alert("answer wrong:"+array);
        });

        $('#out_button').click(function(){
          $('[name="gamer"]').each(function(){
            if (this.checked) {
              CM.unreg('origin_'+this.value);
              this.disabled = true;
            }
          });
          var array = afterAction(this);
          for (var x in array){
            $('#visitor_'+array[x]).attr('style','opacity:0.2');
          }
          //alert("outer:"+array);
        });

        $('#start_button').click(function(){
          if(window.alarm) return;
          $('[name="gamer"]').each(function(){
            if (this.checked) {
              window.chatApp.action(this.value,'start');
              $('#visitor_'+this.value).css("background-color", "");
            }
          });

          $('[name="gamer"]').each(function(){
            if (this.checked) {

              (function (thisvalue) {
               window.alarm = setInterval(function(){
                if (parseInt($('#second_'+thisvalue).text()) != 0){
                  console.log($('#second_'+thisvalue).text());
                  $('#second_'+thisvalue).text(parseInt($('#second_'+thisvalue).text()) - 1);
                }else{
                  clearInterval(window.alarm);
                  window.alarm = null;
                  window.chatApp.action(thisvalue,'stop');
                  receiveSubmitHandler({user_id:thisvalue});
                }
              },1000); 
             })(this.value);

           }
         });
          var array = afterAction(this);
                //alert("stop:"+array);

          //var array = afterAction(this);
          //alert("start:"+array);
        });

      $('#stop_button').click(function(){
            /*
           $('[name="gamer"]').each(function(){
             if (this.checked) {
               window.chatApp.action(this.value,'stop');
             }
           });
           var array = afterAction(this);
           //alert("stop:"+array);
           */
           clearInterval(window.alarm);
           window.alarm = null;
           $('[name="gamer"]').each(function(){
            if (this.checked) {
              window.chatApp.action(this.value,'stop');
              receiveSubmitHandler({user_id:this.value});
            }
          });
           var array = afterAction(this);
         });

    });
      </script>
      <% end %>

app/views/games/server_idioms.html.erb
      <div class="jumbotron">
        <% if !@second.nil?  %>
        <h5 style="position:fixed;">倒數計時 <span id="second" style="color:red"><%= @second %></span> 秒 </h5>
        <% else %>
        <h5>不倒數計時</h5>
        <% end %>
      </div>
      <div id="user_blue"></div>
      <div id="user_black"></div>
        <table id="canvasTable" style="border-collapse:separate;border-spacing:1px 0px;">
          <% (1..8).to_a.each do |x| %>
          <tr>
            <% (1..12).to_a.each do |y| %>
            <td>
              <canvas id="origin_<%= x %>_<%= y %>" style="z-index:1;border:1px solid red"></canvas>
            </td>
            <% end %>
          </tr>
          <% end %>
        </table>
      <div class="row">
        <% @visitors.each do |x| %>
        <div class="visitor col-md-3" id="visitor_<%= x.number %>">
          <div class="row">
            <div class="col-md-1">
              <input type="checkbox" name="gamer" value="<%= x.number %>"/>
            </div>
            <div class="col-md-3">
              <%= render_gamer_photo(x.image,"thumb",50,50) %>
              <p><%= x.name %></p>
            </div>
            <div id="status_<%= x.number %>" class="col-md-2">stop</div>
          </div>
        </div>
        <% end %>
      </div>
      <div class="row">
        <div class="col-md-12">
          <input type="checkbox" id="allGamer"/>全選
          <button id="yes_button" style="font-size:15px;">答對</button>
          <button id="no_button" style="font-size:15px;">答錯</button>
          <button id="start_button" style="font-size:15px;">Start</button>
          <button id="stop_button" style="font-size:15px;">Stop</button>
        </div>
      </div>
      
      <% content_for :javascripts do %>
      <%= javascript_include_tag 'server_idioms' %>
      <script>

      window.timeRemaining = parseInt(<%= @second %>);
      window.alarm = null;

      var afterAction = function(property){
        var array = [];
        $('[name="gamer"]').each(function(){
          if (this.checked) {

            array.push(this.value);
            this.checked = false;
          }
        });
        $('#second').text(window.timeRemaining);
        $('#allGamer').attr('checked',false);

        return array;
      }

      var receiveMoveBlockHandler = function(o){
        var element;
        var offset = $('#canvasTable').offset();
        if (o.user_id % 2 == 0){
          element = $('#user_blue').css({
          border:"2px solid blue",
          width:"95px",
          height:"95px",
          position:"absolute",
          top:(o.block.row-1)*101+offset.top + "px", 
          left:(o.block.column-1)*97+offset.left + "px"
        });
        }else{
          element = $('#user_black').css({
          border:"2px solid black",
          width:"95px",
          height:"95px",
          position:"absolute",
          top:(o.block.row-1)*101+offset.top + "px", 
          left:(o.block.column-1)*97+offset.left + "px"
        });
        }

      };

      var receiveSendTextHandler = function(o){
        var testCan = document.getElementById('origin_'+ o.block.row +'_' + o.block.column);
        var w = $(testCan).width();
        var context = testCan.getContext("2d");
        context.fillStyle = "purple";
        context.font = "bold " + (w * 13 / 15) + "px 標楷體";
        context.fillText(o.text, w / 15, w * 12 / 15);
      };

      var receiveEndRoundHandler = function(o){
        clearInterval(window.alarm);
        window.alarm = null;
        window.chatApp.action(o.user_id,'stop');
        afterAction(this);
      };

      $(document).ready(function() {
        CM.prop({
          width: 500,
          height: 500,
          lineWidth: 15,
          lineColor: '#333333',
          targetZoomScale: 0.035
        });
        <% (1..8).to_a.each do |x| %>
        <% (1..12).to_a.each do |y| %>
        CM.reg('origin_<%= x %>_<%= y %>');
        <% end %>
        <% end %>


        window.chatApp = new ChatApp(500,500,'0');
        window.chatApp.bindEvents();



        $('#allGamer').click(function(){
          $('[name="gamer"]').each((function(toCheck){
            return function(){
              if (this.disabled == false){
                this.checked = toCheck;
              }
            };
          })(this.checked === true));
        });

        $('#yes_button').click(function(){
          var array = afterAction(this);
          for (var x in array){
            var yesImg = $('#yes_' + array[x]);
            yesImg.show();

            setTimeout(( function(item){
              var f = function(){
                item.hide();
              };
              return f
            })(yesImg), 3000);
          }
          //alert("answer right:"+array);
        });

        $('#no_button').click(function(){
          var array = afterAction(this);
          for (var x in array){
            var noImg = $('#no_' + array[x]);
            noImg.show();

            setTimeout((function(item){
              var f = function(){
                item.hide();
              };
              return f
            })(noImg), 3000);
          }
          //alert("answer wrong:"+array);
        });


        $('#start_button').click(function(){
          if(window.alarm) return;
          $('[name="gamer"]').each(function(){
            if (this.checked) {
              window.chatApp.action(this.value,'start');
              $('#visitor_'+this.value).css("background-color", "");
              $('#status_'+this.value).html('** DRAWING **');
            }
          });
          window.alarm = setInterval(function(){
            if (parseInt($('#second').text()) != 0){
              $('#second').text(parseInt($('#second').text()) - 1);
            }else{
              clearInterval(window.alarm);
              window.alarm = null;
              $('[name="gamer"]').each(function(){
                if (this.checked) {
                  window.chatApp.action(this.value,'stop');
                }
              });
              var array = afterAction(this);
              for(var i = 0, len = array.length; i < len; i++){
                $('#status_'+array[i]).html('stop');
              }
              //alert("stop:"+array);
            }
          },1000);
          //var array = afterAction(this);
          //alert("start:"+array);
        });

        // $('#stop_button').click(function(){
        //   $('[name="gamer"]').each(function(){
        //     if (this.checked) {
        //       window.chatApp.action(this.value,'stop');
        //     }
        //   });
        //   var array = afterAction(this);
        //   alert("stop:"+array);
        // });

    });
      </script>
      <% end %>

app/views/games/show.html.erb
<div class="row">
  <div class="col-md-12">
    <%= link_to "回上一頁",'/',class: "btn btn-lg btn-warning"  %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <h1>Game N</h1>
    <h2>參賽人員列表<%= link_to "新增人員",new_game_visitor_path(@game),class: "btn btn-lg btn-info"  %></h2>
    <% if @visitors.present? %>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>代號</th>
          <th>照片</th>
          <th>名字</th>
          <th>加入比賽</th>  
        </tr>
      </thead>
      <tbody>

        <% @visitors.each do |v| %>
        <tr>
          <td><%= v.number %></td>
          <td><%= render_visitor_photo(v.image,"thumb") %></td>
          <td><%= v.name %></td>
          <td><input type="checkbox" name="joinGame" value="<%= v.number %>" /></td>
        </tr>
        <% end %>

        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td><input type="checkbox" id="allJoinGame" />全選</td>
        </tr>
      </tbody>
    </table>
    <% else %>
    尚無參賽人員
    <% end %>
    <br>
    <%= link_to "Stage1","#",id: "stage1",class: "btn btn-lg btn-success"  %>
    <%= link_to "Stage2","#",id: "stage2",class: "btn btn-lg btn-success"  %>
    <%= link_to "Stage3","#",id: "stage3",class: "btn btn-lg btn-success"  %>
  </div>
</div>

<% content_for :javascripts do %>
<script type="text/javascript">
$(document).ready(function(){

  document.getElementById('allJoinGame').onchange = function(event){
    var checkboxes = document.getElementsByName('joinGame');

    for (var i = 0; i < checkboxes.length; i++){
      checkboxes[i].checked = this.checked;
    }
  };

  document.getElementById('stage1').onclick = function(e){
    e.preventDefault();
    var checkboxes = document.getElementsByName('joinGame');

    var join_visitors_number = [];
    for (var i = 0; i < checkboxes.length; i++){
      if(checkboxes[i].checked){
        join_visitors_number.push(checkboxes[i].value);
      }
    }
    location.href = '/games/<%= @game.id %>/stage1?join_visitors_number=' + join_visitors_number;
  }

  document.getElementById('stage2').onclick = function(e){
    e.preventDefault();
    var checkboxes = document.getElementsByName('joinGame');

    var join_visitors_number = [];
    for (var i = 0; i < checkboxes.length; i++){
      if(checkboxes[i].checked){
        join_visitors_number.push(checkboxes[i].value);
      }
    }
    location.href = '/games/<%= @game.id %>/stage2?join_visitors_number=' + join_visitors_number;
  }

  document.getElementById('stage3').onclick = function(e){
    e.preventDefault();
    var checkboxes = document.getElementsByName('joinGame');

    var join_visitors_number = [];
    for (var i = 0; i < checkboxes.length; i++){
      if(checkboxes[i].checked){
        join_visitors_number.push(checkboxes[i].value);
      }
    }
    location.href = '/games/<%= @game.id %>/stage_idioms?join_visitors_number=' + join_visitors_number;
  }
});
</script>
<% end %>

app/views/games/stage1.html.erb
<div class="row">
  <div class="col-md-12">
    <%= link_to "回上一頁",game_path(@game),class: "btn btn-lg btn-warning"  %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <h1>Game <%= @game.id %> > Stage 1</h1>
    <h2>規則</h2>
    <h2>1.不顯示秒數</h2>
    <h2>2.限時 <input id="second" type="number"/> 秒</h2>
    <%= link_to "確認","#",id: "confirm", class: "btn btn-lg btn-success"  %>
  </div>
</div>

<% content_for :javascripts do %>
<script type="text/javascript">
$(document).ready(function(){

  document.getElementById('confirm').onclick = function(e){
    e.preventDefault();
    var second = document.getElementById('second');
    location.href = '/games/<%= @game.id %>/server1?join_visitors_number=<%= @join_visitors_number %>&second='+second.value;
  }
});
</script>
<% end %>